<?php $_code=$this->getMethodCode() ?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <label for="<?php echo $_code ?>_credit_card_type" class="required"><em>*</em><?php echo $this->__('Por favor Escriba su password para verificar:') ?></label>
    <span class="input-box">
        <input type="text" title="<?php echo $this->__('Pass Verification:') ?>" class="input-text required-entry" id="<?php echo $_code ?>_pass_verification" name="payment[pass_verification]" value="<?php echo $this->htmlEscape($this->getInfoData('pass_verification')) ?>" style="width: 150px;" />
    </span>
</ul>
<div>
    <?php echo $this->getMethod()->getConfigData('message');?>
</div>
